#ifndef WIFI_SECRETS_H
#define WIFI_SECRETS_H

#define WIFI_SECRET_SSID "YOUR_WIFI_SSID"
#define WIFI_SECRET_PASSWORD "YOUR_WIFI_PASSWORD"
#define TELEGRAM_BOT_TOKEN "YOUR_BOT_API_TOKEN"
#define TELEGRAM_CHAT_ID "YOUR_CHAT_ID"
#define TELEGRAM_MESSAGE_TEXT "Fall_detected"

#endif
